ValueError: Memory version 2 does not exist in missing_definitions (#155)
* Create draft PR for #133

* Added dst mem ssa label to MLIL_STORE_STRUCT_SSA

* Remove comment

Co-authored-by: NeoQuix <NeoQuix@users.noreply.github.com>
Co-authored-by: Spartak Ehrlich <spartakehrlich@outlook.com>
Co-authored-by: Steffen Enders <steffen.enders@fkie.fraunhofer.de>