RuntimeError: No blocks found for definition in expressionpropagationcommons (#181)
* Create draft PR for #132

* Copy error fix

* Removed unused param

* Nvm, forget sublasses

* Added small test

* Rem include

---------

Co-authored-by: NeoQuix <NeoQuix@users.noreply.github.com>
Co-authored-by: Spartak Ehrlich <spartakehrlich@outlook.com>
Co-authored-by: Spartak Ehrlich <83972469+NeoQuix@users.noreply.github.com>