[Lifter] AttributeError: 'NoneType' object has no attribute 'get_string_after_name' (#302)
* Create draft PR for #301

* Check if expr_type is set

---------

Co-authored-by: NeoQuix <NeoQuix@users.noreply.github.com>
Co-authored-by: Spartak Ehrlich <spartakehrlich@outlook.com>
Co-authored-by: Niklas Bergmann <97505753+0x6e62@users.noreply.github.com>